// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR        ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDPATHPARAM     ErrorResponseErrorCode = "INVALID_PATH_PARAM"
	INVALIDQUERYPARAM    ErrorResponseErrorCode = "INVALID_QUERY_PARAM"
	INVALIDSEARCHQUERY   ErrorResponseErrorCode = "INVALID_SEARCH_QUERY"
	INVALIDUSERNAME      ErrorResponseErrorCode = "INVALID_USERNAME"
	KEYNOTFOUND          ErrorResponseErrorCode = "KEY_NOT_FOUND"
	PROFILENOTFOUND      ErrorResponseErrorCode = "PROFILE_NOT_FOUND"
	PROVIDERFORBIDDEN    ErrorResponseErrorCode = "PROVIDER_FORBIDDEN"
	PROVIDERNOTCONNECTED ErrorResponseErrorCode = "PROVIDER_NOT_CONNECTED"
	PROVIDERUNAVAILABLE  ErrorResponseErrorCode = "PROVIDER_UNAVAILABLE"
	UNAUTHORIZED         ErrorResponseErrorCode = "UNAUTHORIZED"
	USERNAMETAKEN        ErrorResponseErrorCode = "USERNAME_TAKEN"
)

// Defines values for KeyType.
const (
	Gpg KeyType = "gpg"
	Ssh KeyType = "ssh"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// DocumentationUrl Link to API documentation
	DocumentationUrl string `json:"documentation_url"`
	Error            struct {
		// Code Error code
		Code ErrorResponseErrorCode `json:"code"`

		// Details Technical details about the error
		Details *string `json:"details,omitempty"`

		// Message Human-readable error message
		Message string `json:"message"`

		// Path Request path that caused the error
		Path string `json:"path"`

		// Suggestion Suggestion for fixing the error
		Suggestion *string `json:"suggestion,omitempty"`

		// Timestamp Error timestamp
		Timestamp time.Time `json:"timestamp"`
	} `json:"error"`

	// RequestId Unique request identifier
	RequestId openapi_types.UUID `json:"request_id"`

	// Status HTTP status text
	Status string `json:"status"`

	// StatusCode HTTP status code
	StatusCode int `json:"status_code"`
}

// ErrorResponseErrorCode Error code
type ErrorResponseErrorCode string

// GPGMetadata GPG key specific metadata
type GPGMetadata struct {
	// Algorithm GPG key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Capabilities Key capabilities (sign, certify, encrypt_comms, encrypt_storage, authenticate)
	Capabilities *[]string `json:"capabilities,omitempty"`

	// ExpiresAt Key expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`

	// UserIds GPG user IDs (usually email addresses)
	UserIds *[]string `json:"user_ids,omitempty"`
}

// GPGPublicKey GPG public key with embedded metadata
type GPGPublicKey struct {
	// Algorithm GPG key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Capabilities Key capabilities
	Capabilities *[]string `json:"capabilities,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Key expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Fingerprint Key fingerprint
	Fingerprint string `json:"fingerprint"`

	// Id Unique identifier for the public key
	Id openapi_types.UUID `json:"id"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`

	// KeyData Raw key data (base64 encoded)
	KeyData string `json:"key_data"`

	// Source Key source information
	Source *Source `json:"source,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// UserIds GPG user IDs (usually email addresses)
	UserIds *[]string `json:"user_ids,omitempty"`
}

// KeyType Type of public key
type KeyType string

// PublicKey defines model for PublicKey.
type PublicKey struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Fingerprint Key fingerprint
	Fingerprint string `json:"fingerprint"`

	// GpgMetadata GPG key specific metadata
	GpgMetadata *GPGMetadata `json:"gpg_metadata,omitempty"`

	// Id Unique identifier for the public key
	Id openapi_types.UUID `json:"id"`

	// KeyData Raw key data
	KeyData string `json:"key_data"`

	// KeyType Type of public key
	KeyType KeyType `json:"key_type"`

	// Source Key source information
	Source *Source `json:"source,omitempty"`

	// SourceId Reference to the source (provider/user)
	SourceId openapi_types.UUID `json:"source_id"`

	// SshMetadata SSH key specific metadata
	SshMetadata *SSHMetadata `json:"ssh_metadata,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// SSHMetadata SSH key specific metadata
type SSHMetadata struct {
	// Algorithm SSH key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Comment Comment from the SSH key
	Comment *string `json:"comment,omitempty"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`
}

// SSHPublicKey SSH public key with embedded metadata
type SSHPublicKey struct {
	// Algorithm SSH key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Comment Comment from the SSH key
	Comment *string `json:"comment,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Fingerprint Key fingerprint
	Fingerprint string `json:"fingerprint"`

	// Id Unique identifier for the public key
	Id openapi_types.UUID `json:"id"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`

	// KeyData Raw key data (base64 encoded)
	KeyData string `json:"key_data"`

	// Source Key source information
	Source *Source `json:"source,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// Source Key source information
type Source struct {
	// Id Source identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Provider Provider name
	Provider *string `json:"provider,omitempty"`

	// Uri Source URL
	Uri *string `json:"uri,omitempty"`

	// UserId Provider user ID
	UserId *string `json:"user_id,omitempty"`

	// Username Username
	Username *string `json:"username,omitempty"`
}
