// Package common provides primitives to interact with the openapi HttpServer API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR      ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDPATHPARAM   ErrorResponseErrorCode = "INVALID_PATH_PARAM"
	INVALIDQUERYPARAM  ErrorResponseErrorCode = "INVALID_QUERY_PARAM"
	INVALIDSEARCHQUERY ErrorResponseErrorCode = "INVALID_SEARCH_QUERY"
)

// Defines values for SSHKeyType.
const (
	EcdsaSha2Nistp256 SSHKeyType = "ecdsa-sha2-nistp256"
	EcdsaSha2Nistp384 SSHKeyType = "ecdsa-sha2-nistp384"
	EcdsaSha2Nistp521 SSHKeyType = "ecdsa-sha2-nistp521"
	SshEd25519        SSHKeyType = "ssh-ed25519"
	SshRsa            SSHKeyType = "ssh-rsa"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// DocumentationUrl Link to API documentation
	DocumentationUrl string `json:"documentation_url"`
	Error            struct {
		// Code Error code
		Code ErrorResponseErrorCode `json:"code"`

		// Details Technical details about the error
		Details *string `json:"details,omitempty"`

		// Message Human-readable error message
		Message string `json:"message"`

		// Path Request path that caused the error
		Path string `json:"path"`

		// Suggestion Suggestion for fixing the error
		Suggestion *string `json:"suggestion,omitempty"`

		// Timestamp Error timestamp
		Timestamp time.Time `json:"timestamp"`
	} `json:"error"`

	// RequestId Unique request identifier
	RequestId openapi_types.UUID `json:"request_id"`

	// Status HttpServer status text
	Status string `json:"status"`

	// StatusCode HttpServer status code
	StatusCode int `json:"status_code"`
}

// ErrorResponseErrorCode Error code
type ErrorResponseErrorCode string

// SSHKey defines model for SSHKey.
type SSHKey struct {
	// Comment Comment from the SSH key
	Comment *string `json:"comment,omitempty"`

	// Id Unique identifier for the SSH key
	Id openapi_types.UUID `json:"id"`

	// Key SSH public key bytes
	Key []byte `json:"key"`

	// Options SSH key options
	Options *[]string `json:"options,omitempty"`

	// Provider Provider name
	Provider string `json:"provider"`

	// Source Source URL where the key was fetched
	Source string `json:"source"`

	// Type SSH key type
	Type SSHKeyType `json:"type"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// Username Username associated with the SSH key
	Username string `json:"username"`
}

// SSHKeyType SSH key type
type SSHKeyType string
