// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package public

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	externalRef0 "github.com/merlindorin/sshark-api/api/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlAPIV1 defines the Server URL for API v1
const ServerUrlAPIV1 = "/api/v1"

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Duration Query execution duration in nanoseconds
	Duration int `json:"duration"`

	// Entities List of SSH keys matching the search query
	Entities []externalRef0.SSHKey `json:"entities"`

	// Limit Maximum number of results returned
	Limit int `json:"limit"`

	// Offset Number of results skipped
	Offset int `json:"offset"`

	// Query The search query that was executed
	Query string `json:"query"`

	// Total Total number of results matching the query
	Total int `json:"total"`
}

// Statistics defines model for Statistics.
type Statistics struct {
	// TotalKeys Total number of SSH keys indexed
	TotalKeys int `json:"total_keys"`

	// TotalProviders Total number of providers
	TotalProviders int `json:"total_providers"`

	// TotalUsernames Total number of unique usernames
	TotalUsernames int `json:"total_usernames"`
}

// SearchKeysParams defines parameters for SearchKeys.
type SearchKeysParams struct {
	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search SSH keys
	// (GET /search/{query})
	SearchKeys(c *gin.Context, query string, params SearchKeysParams)
	// Get SSH key by ID
	// (GET /sshkeys/{id})
	GetSSHKeyById(c *gin.Context, id openapi_types.UUID)
	// Get statistics
	// (GET /stats)
	GetStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SearchKeys operation middleware
func (siw *ServerInterfaceWrapper) SearchKeys(c *gin.Context) {

	var err error

	// ------------- Path parameter "query" -------------
	var query string

	err = runtime.BindStyledParameterWithOptions("simple", "query", c.Param("query"), &query, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchKeys(c, query, params)
}

// GetSSHKeyById operation middleware
func (siw *ServerInterfaceWrapper) GetSSHKeyById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSSHKeyById(c, id)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/search/:query", wrapper.SearchKeys)
	router.GET(options.BaseURL+"/sshkeys/:id", wrapper.GetSSHKeyById)
	router.GET(options.BaseURL+"/stats", wrapper.GetStats)
}
