// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package public

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	externalRef0 "github.com/merlindorin/sshark-api/api/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlAPIV1 defines the Server URL for API v1
const ServerUrlAPIV1 = "/api/v1"

// Defines values for FacetType.
const (
	Value FacetType = "value"
)

// Defines values for SearchGPGKeysParamsFields.
const (
	SearchGPGKeysParamsFieldsAlgorithm      SearchGPGKeysParamsFields = "algorithm"
	SearchGPGKeysParamsFieldsCapabilities   SearchGPGKeysParamsFields = "capabilities"
	SearchGPGKeysParamsFieldsFingerprint    SearchGPGKeysParamsFields = "fingerprint"
	SearchGPGKeysParamsFieldsId             SearchGPGKeysParamsFields = "id"
	SearchGPGKeysParamsFieldsKeyBits        SearchGPGKeysParamsFields = "key_bits"
	SearchGPGKeysParamsFieldsSourceProvider SearchGPGKeysParamsFields = "source.provider"
	SearchGPGKeysParamsFieldsSourceUri      SearchGPGKeysParamsFields = "source.uri"
	SearchGPGKeysParamsFieldsSourceUserId   SearchGPGKeysParamsFields = "source.user_id"
	SearchGPGKeysParamsFieldsSourceUsername SearchGPGKeysParamsFields = "source.username"
	SearchGPGKeysParamsFieldsUserIds        SearchGPGKeysParamsFields = "user_ids"
)

// Defines values for SearchSSHKeysParamsFields.
const (
	SearchSSHKeysParamsFieldsAlgorithm      SearchSSHKeysParamsFields = "algorithm"
	SearchSSHKeysParamsFieldsComment        SearchSSHKeysParamsFields = "comment"
	SearchSSHKeysParamsFieldsFingerprint    SearchSSHKeysParamsFields = "fingerprint"
	SearchSSHKeysParamsFieldsId             SearchSSHKeysParamsFields = "id"
	SearchSSHKeysParamsFieldsKeyBits        SearchSSHKeysParamsFields = "key_bits"
	SearchSSHKeysParamsFieldsSourceProvider SearchSSHKeysParamsFields = "source.provider"
	SearchSSHKeysParamsFieldsSourceUri      SearchSSHKeysParamsFields = "source.uri"
	SearchSSHKeysParamsFieldsSourceUserId   SearchSSHKeysParamsFields = "source.user_id"
	SearchSSHKeysParamsFieldsSourceUsername SearchSSHKeysParamsFields = "source.username"
)

// Facet defines model for Facet.
type Facet struct {
	Data []FacetValue `json:"data"`

	// Type Facet type
	Type FacetType `json:"type"`
}

// FacetType Facet type
type FacetType string

// FacetValue defines model for FacetValue.
type FacetValue struct {
	// Count Number of occurrences
	Count int `json:"count"`

	// Value Facet value
	Value string `json:"value"`
}

// GPGSearchResponse defines model for GPGSearchResponse.
type GPGSearchResponse struct {
	// Duration Query execution duration in nanoseconds
	Duration int `json:"duration"`

	// Entities List of GPG keys matching the search query
	Entities []externalRef0.GPGPublicKey `json:"entities"`

	// Limit Maximum number of results returned
	Limit int `json:"limit"`

	// Offset Number of results skipped
	Offset int `json:"offset"`

	// Query The search query that was executed
	Query string `json:"query"`

	// Total Total number of results matching the query
	Total int `json:"total"`
}

// SSHSearchResponse defines model for SSHSearchResponse.
type SSHSearchResponse struct {
	// Duration Query execution duration in nanoseconds
	Duration int `json:"duration"`

	// Entities List of SSH keys matching the search query
	Entities []externalRef0.SSHPublicKey `json:"entities"`

	// Limit Maximum number of results returned
	Limit int `json:"limit"`

	// Offset Number of results skipped
	Offset int `json:"offset"`

	// Query The search query that was executed
	Query string `json:"query"`

	// Total Total number of results matching the query
	Total int `json:"total"`
}

// Statistics defines model for Statistics.
type Statistics struct {
	Facets map[string][]Facet `json:"facets"`
}

// SearchGPGKeysParams defines parameters for SearchGPGKeys.
type SearchGPGKeysParams struct {
	// Q Advanced search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Query Basic search term (searches across specified fields with OR)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Fields Fields to search in basic mode (comma-separated or repeated).
	Fields *[]SearchGPGKeysParamsFields `form:"fields,omitempty" json:"fields,omitempty"`

	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchGPGKeysParamsFields defines parameters for SearchGPGKeys.
type SearchGPGKeysParamsFields string

// SearchSSHKeysParams defines parameters for SearchSSHKeys.
type SearchSSHKeysParams struct {
	// Q Advanced search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Query Basic search term (searches across specified fields with OR)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Fields Fields to search in basic mode (comma-separated or repeated).
	Fields *[]SearchSSHKeysParamsFields `form:"fields,omitempty" json:"fields,omitempty"`

	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchSSHKeysParamsFields defines parameters for SearchSSHKeys.
type SearchSSHKeysParamsFields string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search GPG keys
	// (GET /gpg/search)
	SearchGPGKeys(c *gin.Context, params SearchGPGKeysParams)
	// Get public key by ID
	// (GET /publickeys/{id})
	GetPublicKeyById(c *gin.Context, id openapi_types.UUID)
	// Search SSH keys
	// (GET /ssh/search)
	SearchSSHKeys(c *gin.Context, params SearchSSHKeysParams)
	// Get statistics
	// (GET /stats)
	GetStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SearchGPGKeys operation middleware
func (siw *ServerInterfaceWrapper) SearchGPGKeys(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchGPGKeysParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", c.Request.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", false, false, "fields", c.Request.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fields: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchGPGKeys(c, params)
}

// GetPublicKeyById operation middleware
func (siw *ServerInterfaceWrapper) GetPublicKeyById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicKeyById(c, id)
}

// SearchSSHKeys operation middleware
func (siw *ServerInterfaceWrapper) SearchSSHKeys(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchSSHKeysParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", c.Request.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", false, false, "fields", c.Request.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fields: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchSSHKeys(c, params)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/gpg/search", wrapper.SearchGPGKeys)
	router.GET(options.BaseURL+"/publickeys/:id", wrapper.GetPublicKeyById)
	router.GET(options.BaseURL+"/ssh/search", wrapper.SearchSSHKeys)
	router.GET(options.BaseURL+"/stats", wrapper.GetStats)
}
