// Package authenticated provides primitives to interact with the openapi HttpServer API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package authenticated

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClerkAuthScopes = "ClerkAuth.Scopes"
)

// ServerUrlAPIV1 defines the Server URL for API v1
const ServerUrlAPIV1 = "/api/v1"

// Defines values for ApiKeyObject.
const (
	ApiKeyObjectApiKey ApiKeyObject = "api_key"
)

// Defines values for ApiKeyType.
const (
	ApiKeyTypeApiKey ApiKeyType = "api_key"
)

// Defines values for ApiKeyWithSecretObject.
const (
	ApiKeyWithSecretObjectApiKey ApiKeyWithSecretObject = "api_key"
)

// Defines values for ApiKeyWithSecretType.
const (
	ApiKeyWithSecretTypeApiKey ApiKeyWithSecretType = "api_key"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	// Claims Custom claims associated with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// CreatedAt Unix timestamp of creation
	CreatedAt int64 `json:"created_at"`

	// CreatedBy User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration
	Expiration *int64 `json:"expiration,omitempty"`

	// Expired Whether the API key has expired
	Expired bool `json:"expired"`

	// Id API key ID
	Id string `json:"id"`

	// LastUsedAt Unix timestamp of last use
	LastUsedAt *int64 `json:"last_used_at,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Object Object type identifier
	Object ApiKeyObject `json:"object"`

	// RevocationReason Reason for revocation if revoked
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// Revoked Whether the API key has been revoked
	Revoked bool `json:"revoked"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`

	// Subject User ID associated with this API key
	Subject string `json:"subject"`

	// Type API key type
	Type ApiKeyType `json:"type"`

	// UpdatedAt Unix timestamp of last update
	UpdatedAt int64 `json:"updated_at"`
}

// ApiKeyObject Object type identifier
type ApiKeyObject string

// ApiKeyType API key type
type ApiKeyType string

// ApiKeyWithSecret defines model for ApiKeyWithSecret.
type ApiKeyWithSecret struct {
	// Claims Custom claims associated with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// CreatedAt Unix timestamp of creation
	CreatedAt int64 `json:"created_at"`

	// CreatedBy User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration
	Expiration *int64 `json:"expiration,omitempty"`

	// Expired Whether the API key has expired
	Expired bool `json:"expired"`

	// Id API key ID
	Id string `json:"id"`

	// LastUsedAt Unix timestamp of last use
	LastUsedAt *int64 `json:"last_used_at,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Object Object type identifier
	Object ApiKeyWithSecretObject `json:"object"`

	// RevocationReason Reason for revocation if revoked
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// Revoked Whether the API key has been revoked
	Revoked bool `json:"revoked"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`

	// Secret API key secret (only returned on creation)
	Secret string `json:"secret"`

	// Subject User ID associated with this API key
	Subject string `json:"subject"`

	// Type API key type
	Type ApiKeyWithSecretType `json:"type"`

	// UpdatedAt Unix timestamp of last update
	UpdatedAt int64 `json:"updated_at"`
}

// ApiKeyWithSecretObject Object type identifier
type ApiKeyWithSecretObject string

// ApiKeyWithSecretType API key type
type ApiKeyWithSecretType string

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// Claims Custom claims to associate with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration (optional)
	Expiration *int64 `json:"expiration,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	// CreatedAt Unix timestamp of user creation
	CreatedAt int64 `json:"created_at"`

	// Email Primary email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// FirstName User's first name
	FirstName *string `json:"first_name,omitempty"`

	// Id User ID
	Id string `json:"id"`

	// ImageUrl Avatar URL
	ImageUrl *string `json:"image_url,omitempty"`

	// LastName User's last name
	LastName *string `json:"last_name,omitempty"`

	// Username Username
	Username *string `json:"username,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get authenticated user info
	// (GET /me)
	GetMe(c *gin.Context)
	// List API keys
	// (GET /me/apikeys)
	ListApiKeys(c *gin.Context)
	// Create API key
	// (POST /me/apikeys)
	CreateApiKey(c *gin.Context)
	// Delete API key
	// (DELETE /me/apikeys/{id})
	DeleteApiKey(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApiKeys(c)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApiKey(c)
}

// DeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiKey(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/me/apikeys", wrapper.ListApiKeys)
	router.POST(options.BaseURL+"/me/apikeys", wrapper.CreateApiKey)
	router.DELETE(options.BaseURL+"/me/apikeys/:id", wrapper.DeleteApiKey)
}
