// Package authenticated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package authenticated

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	externalRef0 "github.com/merlindorin/sshark-api/api/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClerkAuthScopes = "ClerkAuth.Scopes"
)

// ServerUrlAPIV1 defines the Server URL for API v1
const ServerUrlAPIV1 = "/api/v1"

// Defines values for ApiKeyObject.
const (
	ApiKeyObjectApiKey ApiKeyObject = "api_key"
)

// Defines values for ApiKeyType.
const (
	ApiKeyTypeApiKey ApiKeyType = "api_key"
)

// Defines values for ApiKeyWithSecretObject.
const (
	ApiKeyWithSecretObjectApiKey ApiKeyWithSecretObject = "api_key"
)

// Defines values for ApiKeyWithSecretType.
const (
	ApiKeyWithSecretTypeApiKey ApiKeyWithSecretType = "api_key"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	// Claims Custom claims associated with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// CreatedAt Unix timestamp of creation
	CreatedAt int64 `json:"created_at"`

	// CreatedBy User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration
	Expiration *int64 `json:"expiration,omitempty"`

	// Expired Whether the API key has expired
	Expired bool `json:"expired"`

	// Id API key ID
	Id string `json:"id"`

	// LastUsedAt Unix timestamp of last use
	LastUsedAt *int64 `json:"last_used_at,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Object Object type identifier
	Object ApiKeyObject `json:"object"`

	// RevocationReason Reason for revocation if revoked
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// Revoked Whether the API key has been revoked
	Revoked bool `json:"revoked"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`

	// Subject User ID associated with this API key
	Subject string `json:"subject"`

	// Type API key type
	Type ApiKeyType `json:"type"`

	// UpdatedAt Unix timestamp of last update
	UpdatedAt int64 `json:"updated_at"`
}

// ApiKeyObject Object type identifier
type ApiKeyObject string

// ApiKeyType API key type
type ApiKeyType string

// ApiKeyWithSecret defines model for ApiKeyWithSecret.
type ApiKeyWithSecret struct {
	// Claims Custom claims associated with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// CreatedAt Unix timestamp of creation
	CreatedAt int64 `json:"created_at"`

	// CreatedBy User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration
	Expiration *int64 `json:"expiration,omitempty"`

	// Expired Whether the API key has expired
	Expired bool `json:"expired"`

	// Id API key ID
	Id string `json:"id"`

	// LastUsedAt Unix timestamp of last use
	LastUsedAt *int64 `json:"last_used_at,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Object Object type identifier
	Object ApiKeyWithSecretObject `json:"object"`

	// RevocationReason Reason for revocation if revoked
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// Revoked Whether the API key has been revoked
	Revoked bool `json:"revoked"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`

	// Secret API key secret (only returned on creation)
	Secret string `json:"secret"`

	// Subject User ID associated with this API key
	Subject string `json:"subject"`

	// Type API key type
	Type ApiKeyWithSecretType `json:"type"`

	// UpdatedAt Unix timestamp of last update
	UpdatedAt int64 `json:"updated_at"`
}

// ApiKeyWithSecretObject Object type identifier
type ApiKeyWithSecretObject string

// ApiKeyWithSecretType API key type
type ApiKeyWithSecretType string

// ConnectedAccount A provider account the authenticated user has proven they own
type ConnectedAccount struct {
	// CanRevoke Whether sshark holds a delegated credential able to delete keys at the provider.
	// When false, missing_scopes explains what the grant lacks.
	CanRevoke bool `json:"can_revoke"`

	// MissingScopes OAuth scopes the grant is missing to manage keys
	MissingScopes *[]string `json:"missing_scopes,omitempty"`

	// Provider Provider name
	Provider string `json:"provider"`

	// Uri Profile URL at the provider
	Uri *string `json:"uri,omitempty"`

	// Username Login at the provider
	Username string `json:"username"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// Claims Custom claims to associate with the API key
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// Description API key description
	Description *string `json:"description,omitempty"`

	// Expiration Unix timestamp of expiration (optional)
	Expiration *int64 `json:"expiration,omitempty"`

	// Name API key name
	Name string `json:"name"`

	// Scopes API key scopes
	Scopes *[]string `json:"scopes,omitempty"`
}

// MyGPGKey A GPG public key attributed to the authenticated user
type MyGPGKey struct {
	// Algorithm GPG key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Capabilities Key capabilities
	Capabilities *[]string `json:"capabilities,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Key expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Fingerprint Key fingerprint
	Fingerprint string `json:"fingerprint"`

	// Id Unique identifier for the public key
	Id openapi_types.UUID `json:"id"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`

	// KeyData Raw key data (base64 encoded)
	KeyData string `json:"key_data"`

	// Revocable Whether this key can be revoked through sshark
	Revocable bool `json:"revocable"`

	// Source Key source information
	Source *externalRef0.Source `json:"source,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// UserIds GPG user IDs (usually email addresses)
	UserIds *[]string `json:"user_ids,omitempty"`

	// Verified Whether the key belongs to a provider account the user proved they own by
	// signing in with it.
	Verified bool `json:"verified"`
}

// MyKeysResponse defines model for MyKeysResponse.
type MyKeysResponse struct {
	// Accounts Provider accounts the user has connected
	Accounts []ConnectedAccount `json:"accounts"`

	// GpgKeys GPG keys attributed to the user
	GpgKeys []MyGPGKey `json:"gpg_keys"`

	// RefreshedAt When the keys were last pulled from the providers, set by a refresh
	RefreshedAt *time.Time `json:"refreshed_at,omitempty"`

	// SshKeys SSH keys attributed to the user
	SshKeys []MySSHKey `json:"ssh_keys"`
}

// MyProfile The signed-in user's SShark account
type MyProfile struct {
	// ProfileUrl Path of the public profile
	ProfileUrl string `json:"profile_url"`

	// Username The username the public profile is served from
	Username string `json:"username"`
}

// MySSHKey An SSH public key attributed to the authenticated user
type MySSHKey struct {
	// Algorithm SSH key algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Comment Comment from the SSH key
	Comment *string `json:"comment,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Fingerprint Key fingerprint
	Fingerprint string `json:"fingerprint"`

	// Id Unique identifier for the public key
	Id openapi_types.UUID `json:"id"`

	// KeyBits Key size in bits
	KeyBits *int `json:"key_bits,omitempty"`

	// KeyData Raw key data (base64 encoded)
	KeyData string `json:"key_data"`

	// Revocable Whether this key can be revoked through sshark
	Revocable bool `json:"revocable"`

	// Source Key source information
	Source *externalRef0.Source `json:"source,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// Verified Whether the key belongs to a provider account the user proved they own by
	// signing in with it.
	Verified bool `json:"verified"`
}

// SetUsernameRequest defines model for SetUsernameRequest.
type SetUsernameRequest struct {
	// Username The username to claim
	Username string `json:"username"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	// CreatedAt Unix timestamp of user creation
	CreatedAt int64 `json:"created_at"`

	// Email Primary email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// FirstName User's first name
	FirstName *string `json:"first_name,omitempty"`

	// Id User ID
	Id string `json:"id"`

	// ImageUrl Avatar URL
	ImageUrl *string `json:"image_url,omitempty"`

	// LastName User's last name
	LastName *string `json:"last_name,omitempty"`

	// ProfileUrl Path of the public profile
	ProfileUrl *string `json:"profile_url,omitempty"`

	// Username The SShark username this account's public profile is served from
	Username *string `json:"username,omitempty"`
}

// UsernameAvailability defines model for UsernameAvailability.
type UsernameAvailability struct {
	// Available Whether the username can be claimed
	Available bool `json:"available"`

	// Reason Why the username cannot be claimed
	Reason *string `json:"reason,omitempty"`

	// Username The username that was checked
	Username string `json:"username"`
}

// CheckUsernameAvailableParams defines parameters for CheckUsernameAvailable.
type CheckUsernameAvailableParams struct {
	// Username The username to check
	Username string `form:"username" json:"username"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// SetMyUsernameJSONRequestBody defines body for SetMyUsername for application/json ContentType.
type SetMyUsernameJSONRequestBody = SetUsernameRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get authenticated user info
	// (GET /me)
	GetMe(c *gin.Context)
	// List API keys
	// (GET /me/apikeys)
	ListApiKeys(c *gin.Context)
	// Create API key
	// (POST /me/apikeys)
	CreateApiKey(c *gin.Context)
	// Delete API key
	// (DELETE /me/apikeys/{id})
	DeleteApiKey(c *gin.Context, id string)
	// List the authenticated user's public keys
	// (GET /me/keys)
	ListMyKeys(c *gin.Context)
	// Refresh the authenticated user's public keys
	// (POST /me/keys/refresh)
	RefreshMyKeys(c *gin.Context)
	// Revoke a public key
	// (DELETE /me/keys/{id})
	RevokeMyKey(c *gin.Context, id openapi_types.UUID)
	// Release your SShark profile
	// (DELETE /me/profile)
	DeleteMyProfile(c *gin.Context)
	// Claim or change your username
	// (PUT /me/username)
	SetMyUsername(c *gin.Context)
	// Check whether a username can be claimed
	// (GET /me/username/available)
	CheckUsernameAvailable(c *gin.Context, params CheckUsernameAvailableParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApiKeys(c)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApiKey(c)
}

// DeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiKey(c, id)
}

// ListMyKeys operation middleware
func (siw *ServerInterfaceWrapper) ListMyKeys(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyKeys(c)
}

// RefreshMyKeys operation middleware
func (siw *ServerInterfaceWrapper) RefreshMyKeys(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshMyKeys(c)
}

// RevokeMyKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeMyKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeMyKey(c, id)
}

// DeleteMyProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteMyProfile(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMyProfile(c)
}

// SetMyUsername operation middleware
func (siw *ServerInterfaceWrapper) SetMyUsername(c *gin.Context) {

	c.Set(ClerkAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetMyUsername(c)
}

// CheckUsernameAvailable operation middleware
func (siw *ServerInterfaceWrapper) CheckUsernameAvailable(c *gin.Context) {

	var err error

	c.Set(ClerkAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckUsernameAvailableParams

	// ------------- Required query parameter "username" -------------

	if paramValue := c.Query("username"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument username is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "username", c.Request.URL.Query(), &params.Username)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter username: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckUsernameAvailable(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/me/apikeys", wrapper.ListApiKeys)
	router.POST(options.BaseURL+"/me/apikeys", wrapper.CreateApiKey)
	router.DELETE(options.BaseURL+"/me/apikeys/:id", wrapper.DeleteApiKey)
	router.GET(options.BaseURL+"/me/keys", wrapper.ListMyKeys)
	router.POST(options.BaseURL+"/me/keys/refresh", wrapper.RefreshMyKeys)
	router.DELETE(options.BaseURL+"/me/keys/:id", wrapper.RevokeMyKey)
	router.DELETE(options.BaseURL+"/me/profile", wrapper.DeleteMyProfile)
	router.PUT(options.BaseURL+"/me/username", wrapper.SetMyUsername)
	router.GET(options.BaseURL+"/me/username/available", wrapper.CheckUsernameAvailable)
}
