{{- if and .Values.clerk.token (not .Values.clerk.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sshark-api.fullname" . }}-clerk-token
  labels:
    {{- include "sshark-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  clerk-token: {{ .Values.clerk.token | quote }}
{{- end }}
