{{- if .Values.dragonfly.enabled }}
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ include "sshark-api.fullname" . }}-dragonfly
  labels:
    {{- include "sshark-api.labels" . | nindent 4 }}
  {{- with .Values.dragonfly.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.dragonfly.replicas }}
  {{- with .Values.dragonfly.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.dragonfly.storage.enabled .Values.dragonfly.snapshot.enabled }}
  snapshot:
    {{- if .Values.dragonfly.snapshot.enabled }}
    {{- if .Values.dragonfly.snapshot.cron }}
    cron: {{ .Values.dragonfly.snapshot.cron | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.dragonfly.storage.existingPersistentVolumeClaimName }}
    existingPersistentVolumeClaimName: {{ .Values.dragonfly.storage.existingPersistentVolumeClaimName | quote }}
    {{- else if .Values.dragonfly.storage.enabled }}
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.dragonfly.storage.size }}
      {{- if .Values.dragonfly.storage.storageClassName }}
      storageClassName: {{ .Values.dragonfly.storage.storageClassName | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.dragonfly.args }}
  args:
    {{- toYaml .Values.dragonfly.args | nindent 4 }}
  {{- end }}
  {{- if .Values.dragonfly.skipFSGroup }}
  skipFSGroup: {{ .Values.dragonfly.skipFSGroup }}
  {{- end }}
{{- end }}
